In [2]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3])
print(arr)

arr = np.zeros(4)
print(arr)

arr = np.arange(1, 4, 2)
print(arr)

arr = np.random.rand(2)
print(arr)

arr = np.empty(3)
print(arr)

[1 2 3]
[0. 0. 0. 0.]
[1 3]
[0.22709166 0.55338859]
[4.9e-324 9.9e-324 1.5e-323]


In [6]:
arr = np.array([[1, 2, 3], [1, 2, 3]], dtype=float)
print(arr)

arr = np.zeros((2, 4))
print(arr)

arr = np.full((1, 4), 2.0)
print(arr)

[[1. 2. 3.]
 [1. 2. 3.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[2. 2. 2. 2.]]


In [14]:
arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0]
])

print(arr)
print(arr[0][1])
print(arr[1][1])
print(arr[0][0::2])
print(arr[0][0:1])
print(arr[0::,1:3])

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
2.0
6.0
[1. 3.]
[1.]
[[2. 3.]
 [6. 7.]]


In [ ]:
# np.where(condition, x, y) if condition true -> x else -> y
arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0]
])

print(np.where(arr %2 == 0, "Even", "Odd"))
print(np.where(arr < 5, arr, arr+5))
print(np.where(arr > 5, -1, arr))

[['Odd' 'Even' 'Odd' 'Even']
 ['Odd' 'Even' 'Odd' 'Even']]
[[ 1.  2.  3.  4.]
 [10. 11. 12. 13.]]
[[ 1.  2.  3.  4.]
 [ 5. -1. -1. -1.]]
1


In [29]:
a_data = np.array([6, 5, 7, 1, 9, 2])
deleted_index = np.where(a_data == 5)
a_data = np.delete(a_data, deleted_index)
print(a_data)

[6 7 1 9 2]


In [ ]:
a_data = np.array([6, 5, 7, 1, 9, 2])
# Xóa phần tử thứ 1 và 2
a_data = np.concatenate((a_data[:1], a_data[3:]))
print(a_data)

[6 1 9 2]
0


In [38]:
a_data = np.array([6, 5, 7, 1, 9, 2])
res = np.where(a_data==1)[0][0]
print(res)
count1 = np.count_nonzero(a_data==7)
print(count1)
count2 = np.sum(a_data==7)
print(count2)

3
1
1


In [40]:
# zip() built-in function
l1 = [1, 2, 3]
l2 = [5, 6, 7]

length = len(l1)
for i in range(length):
    print(l1[i], l2[i])

for v1, v2 in zip(l1, l2):
    print(v1, v2)


1 5
2 6
3 7
1 5
2 6
3 7


In [49]:
# zip() like operation in numpy
arr1 = np.array([1, 2, 3])
arr2 = np.array([5, 6, 7])

arr3 = arr1.reshape(1,3)
print(arr1.shape)
print(arr3)
zipped_arr = np.dstack((arr1, arr2))[0]
print(zipped_arr)

(3,)
[[1 2 3]]
[[1 5]
 [2 6]
 [3 7]]


In [51]:
# enumerate() get index and value
data = [6, 1, 7]

for index in range(len(data)):
    print(index, data[index])

for index, value in enumerate(data):
    print(index, value)

0 6
1 1
2 7
0 6
1 1
2 7


In [52]:
# np.ndenumerate()
arr1 = np.array([1, 3, 4])
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 1
(1,) 3
(2,) 4


In [53]:
# Memory usage comparison between list and np.array
import sys

lst = [1, 2, 3, 4]
arr = np.array([1, 2, 3, 4])

print("List memory size: ", sys.getsizeof(lst)+sum(sys.getsizeof(x) for x in lst))
print("NumPy array memory size: ", arr.nbytes)

List memory size:  200
NumPy array memory size:  32


In [54]:
# performance
import time

lst = list(range(1000000))
arr = np.array(lst)

# List multiplication
start = time.time()
lst_result = [x * 2 for x in lst]
end = time.time()
print("List time:", end - start)

# NumPy multiplication
start = time.time()
arr_result = arr * 2
end = time.time()
print("NumPy time:", end - start)


List time: 0.0713355541229248
NumPy time: 0.004518032073974609
