In [2]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3])
print(arr)

arr = np.zeros(4)
print(arr)

arr = np.arange(1, 4, 2)
print(arr)

arr = np.random.rand(2)
print(arr)

arr = np.empty(3)
print(arr)

[1 2 3]
[0. 0. 0. 0.]
[1 3]
[0.22709166 0.55338859]
[4.9e-324 9.9e-324 1.5e-323]


In [6]:
arr = np.array([[1, 2, 3], [1, 2, 3]], dtype=float)
print(arr)

arr = np.zeros((2, 4))
print(arr)

arr = np.full((1, 4), 2.0)
print(arr)

[[1. 2. 3.]
 [1. 2. 3.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[2. 2. 2. 2.]]


In [13]:
arr = np.array([
    [1.0, 2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0, 8.0]
])

print(arr)
print(arr[0][1])
print(arr[1][1])
print(arr[0][0::2])
print(arr[0][0:1])
print(arr[0::][1:3])

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
2.0
6.0
[1. 3.]
[1.]
[[5. 6. 7. 8.]]
